name: Build & Release LuminaSQL

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:

  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Backend EXE
        run: |
          cd backend
          pyinstaller main.py --onefile

      - name: Install Node Modules
        run: npm install

      - name: Build & Publish Electron App
        run: npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || 'mac' }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}